site_name: Comparalyzer Documentation
repo_url: https://gitlab.com/AlexRogalskiy/Comparalyzer
pages:
- Home: index.md
- Dependency Management: dependency.md
- Getting Started: getting-started.md
- User Guide:
  - User Guide: user-guide.md
